variables:
  Build.Repository.Clean: true
  _enableTelemetry: true

  _HelixType: build/product
  ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
    _HelixSource: pr/dotnet/winforms/$(Build.SourceBranch)
  ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    _TeamName: DotNetCore
    _HelixSource: official/dotnet/winforms/$(Build.SourceBranch)

# leave this commented out for now so commits to every branch will trigger a build
#trigger:
#- master

# To be added in the future when VSTS supports this feature
# pr:
# - master

phases:
- template: /eng/build.yml
  parameters:
    name: Windows_NT
    enableTelemetry: $(_enableTelemetry)
    queue:
      # For public or PR jobs, use the hosted pool.  For internal jobs use the internal pool.
      # Will eventually change this to two BYOC pools.
      ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
        name: dotnet-external-temp
      ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
        name: dotnet-internal-temp
      parallel: 99
      matrix:
        Build_Debug:
          _BuildConfig: netcoreapp-Windows_NT-Debug
          _PublishType: none
          _SignType: test
          _DotNetPublishToBlobFeed : false
        Build_Release:
          _BuildConfig: netcoreapp-Windows_NT-Release
          # PRs or external builds are not signed.
          ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
            _PublishType: none
            _SignType: test
            _DotNetPublishToBlobFeed : false
          ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
            _PublishType: blob
            _SignType: test # set to real once our build definition has signing approval
            _DotNetPublishToBlobFeed : true

- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: /eng/common/templates/phases/publish-build-assets.yml
    parameters:
      dependsOn:
        - Windows_NT
      queue:
        name: Hosted VS2017
      configuration: netcoreapp-Windows_NT-Debug