variables:
  Build.Repository.Clean: true
  _enableTelemetry: true

  _HelixType: build/product
  # Change helix sources based on build project/reason
  ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
    _HelixSource: pr/dotnet/winforms/$(Build.SourceBranch)
  ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    _TeamName: DotNetCore
    _HelixSource: official/dotnet/winforms/$(Build.SourceBranch)

# leave this commented out for now so commits to every branch will trigger a build
#trigger:
#- master

# To be added in the future when VSTS supports this feature
# pr:
# - master

phases:
- template: /eng/build.yml
  parameters:
    name: Windows_NT
    enableTelemetry: $(_enableTelemetry)
    queue:
      # If project is public, use the external pool. Otherwise, use internal.
      ${{ if eq(variables['System.TeamProject'], 'public') }}:
        name: dotnet-external-temp
      ${{ if ne(variables['System.TeamProject'], 'public') }}:
        name: dotnet-internal-temp
      parallel: 99
      matrix:
        Build_Debug:
          _BuildConfig: netcoreapp-Windows_NT-Debug
          _PublishType: none
          _SignType: test
          _DotNetPublishToBlobFeed : false
        Build_Release:
          _BuildConfig: netcoreapp-Windows_NT-Release
          # If the project is public or the build is for a PR, test sign and don't publish package updates to dotnet feed.
          # If the project is not public AND the build is NOT for a PR, real sign and publish.
          ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
            _PublishType: none
            _SignType: test
            _DotNetPublishToBlobFeed : false
          ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
            _PublishType: blob
            _SignType: test # set to real once our build definition has signing approval
            _DotNetPublishToBlobFeed : true

# If the project is NOT public AND the build is NOT for a PR, publish build assets 
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - template: /eng/common/templates/phases/publish-build-assets.yml
    parameters:
      dependsOn:
        - Windows_NT
      queue:
        name: Hosted VS2017
      configuration: netcoreapp-Windows_NT-Debug